{
    'name': 'KUMBRA Disponibilidad de Alquiler',
    'version': '18.0.1.4',
    'category': 'Rental',
    'summary': 'Disponibilidad para Alquiler de Embarcaciones',
    'author': 'Renkar',
    'depends': ['base', 'fleet','sale_renting', 'product', 'web','custom_zonas_nav','sale_management'],
    'assets': {
        'web.assets_backend': [
            'custom_rental/static/src/js/range_planner_field.js',
            'custom_rental/static/src/js/refresh.js',
            'custom_rental/static/src/css/range_planner.css',
            'custom_rental/static/src/xml/range_planner_field.xml',
            'custom_rental/static/src/css/turns_view.css',
            'custom_rental/static/src/css/rental_turn.css',
            'custom_rental/static/src/scss/schedule_statusbar.scss',
            'custom_rental/static/src/scss/hide_rental_dates.scss',
            'custom_rental/static/src/scss/rental_badges.scss',
        ],
        'web.assets_qweb': [
            'custom_rental/static/src/xml/range_planner_field.xml',
        ],
    },
    'data': [
        'security/ir.model.access.csv',
        'views/order_views.xml',
        'views/rental_availability_views.xml',
        'views/rental_blocked_period_views.xml',
        'views/block_period_range_wizard_views.xml',
        'views/rental_calendar_event_views.xml',
        #Producto
        'views/product_turns_view.xml',
        'views/product_general_views.xml',
        'views/res_config_settings_views.xml',
        # Turnos & schedules
        'views/sale_order_turn_fields_view.xml',
        'views/sale_order_line_controls_view.xml',
        'views/sale_order_schedule_relaxed.xml',
        'views/sale_order_schedule_state_view.xml',
        'views/rental_order_partner_default.xml',
        'views/sale_order_add_class.xml',
        'views/rental_product_picker_views.xml',
        'views/rental_order_kanban_badges.xml',
        'views/rental_order_search_view.xml',
        'views/rental_order_badges_list_view.xml',
        'data/sale_order_list_status_view.xml',
        'data/rental_action_overrides_list.xml',
    ],
    'installable': True,
    'application': False,
    'license': 'LGPL-3',
}